global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8080"]
  - job_name: order
    static_configs:
      - targets: ["order:8081"]
  - job_name: payment
    static_configs:
      - targets: ["payment:8082"]
  - job_name: inventory
    static_configs:
      - targets: ["inventory:8083"]
  - job_name: notification
    static_configs:
      - targets: ["notification:8084"]
